name: Debug NDK
on: [push]
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT"
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME"
          echo "ANDROID_NDK_LATEST_HOME=$ANDROID_NDK_LATEST_HOME"
          ls -la $ANDROID_NDK_LATEST_HOME
          ls -la $ANDROID_NDK_ROOT || true
